### ISSUE TITLE
Error on invalid argument when triggering login

### ISSUE THREAD

**Issue by kineticac** [torusresearch/customauth-flutter-sdk#12]
When trying to run v2.0.0 on macOS, I get this error when trying to trigger login (google). I haven't tried other verifiers, but this is happening immediately and everytime.

I'm following the `/example` app as well as the readme rules.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument: Map<dynamic, dynamic>
#0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:426:7)
#1      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:423:9)
#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:400:8)
#3      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:421:13)
#4      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:561:18)
#5      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:148:13)
#6      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#7      TorusDirect.triggerLogin (package:torus_direct/torus_direct.dart:53:26)
```

**Comment by kineticac** [comment]
I set my pubspec to grab the latest from master, and this has gone away.

```
  customauth_flutter:
    git:
      url: git@github.com:torusresearch/customauth-flutter-sdk.git
      ref: master
```

It seems like it was fixed, but in pub.dev, the latest version is v2.0.0
